#!/bin/sh
# Build examples/form/build/Guestbook.app — the form example as a macOS app
# bundle, so it launches from the Finder and the Dock with its own name,
# icon and bundle identifier.
#
#   sh examples/form/make-app.sh        # node, through tsx
#   sh examples/form/make-app.sh --bun  # bun runs the JSX itself
#
# The bundle's executable is a three-line script, not a binary and not a
# copy of the runtime. AppKit takes an app's main bundle from CoreFoundation's
# idea of the process path, and for a script that would be the interpreter's
# — the app would be "bun" in the menu bar, iconless, in bun's defaults
# domain. CoreFoundation reads that path from `CFProcessPath` in the
# environment before anything else, and a `#!/usr/bin/env -S` line can set
# it before the interpreter starts; so the shebang names this file as the
# process path and the runtime as the interpreter, and Launch Services then
# checks the process in as the app. Paths are absolute: a shebang sees no
# PATH and no cwd, and Launch Services passes no arguments.
set -e
here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/../.." && pwd)
app="$here/build/Guestbook.app"
exe="$app/Contents/MacOS/Guestbook"

if [ "$1" = "--bun" ]; then
  runtime=$(command -v bun) || { echo "bun not found" >&2; exit 1; }
  # bun reads JSX itself
  load="import('$here/index.jsx');"
else
  runtime=$(command -v node) || { echo "node not found" >&2; exit 1; }
  # tsx, registered by the shim itself through tsx's own API rather than
  # by `--import` on the shebang: a loader named there would transform the
  # shim too, and tsx's lexer for a dynamic import does not survive a
  # shebang line. Registered after the shim has loaded, it sees only the
  # example. By file, since the shim resolves nothing from a cwd it does
  # not control; chained, so the example is not asked for before the
  # loader is in place; by dynamic import throughout, which reads the same
  # whether node takes the shim for a module or for CommonJS.
  load="import('$root/node_modules/tsx/dist/esm/api/index.mjs').then((tsx) => tsx.register()).then(() => import('$here/index.jsx'));"
fi

rm -rf "$app"
mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"
cp "$here/Info.plist" "$app/Contents/Info.plist"
printf 'APPL????' > "$app/Contents/PkgInfo"

# The executable Info.plist names. Plain JS rather than JSX, since a file
# with no extension is read as JS by both runtimes — node decides between
# module and CommonJS by looking at it, so nothing here is written that
# only one of the two allows. The kernel reads the shebang line whole, so
# it has to
# stay under its limit (512 bytes on macOS): three absolute paths fit
# unless the checkout is somewhere very deep.
cat > "$exe" <<SHIM
#!/usr/bin/env -S CFProcessPath=$exe $runtime
// generated by make-app.sh: the bundle executable, see there
process.chdir('$root');
$load
SHIM
chmod +x "$exe"
if [ "$(head -1 "$exe" | wc -c)" -gt 512 ]; then
  echo "the shebang line is over 512 bytes; move the checkout somewhere shallower" >&2
  exit 1
fi

# the icon: the SVG rendered by Quick Look, cut into the sizes an icon set
# wants, packed by iconutil
iconset="$here/build/Guestbook.iconset"
rm -rf "$iconset"; mkdir -p "$iconset"
qlmanage -t -s 1024 -o "$here/build" "$here/icon.svg" >/dev/null 2>&1
master="$here/build/icon.svg.png"
for size in 16 32 128 256 512; do
  sips -z $size $size "$master" --out "$iconset/icon_${size}x${size}.png" >/dev/null
  double=$((size * 2))
  sips -z $double $double "$master" --out "$iconset/icon_${size}x${size}@2x.png" >/dev/null
done
iconutil -c icns "$iconset" -o "$app/Contents/Resources/Guestbook.icns"
rm -rf "$iconset" "$master"

echo "built $app (on $(basename "$runtime"))"
